### ISSUE TITLE
Generate Json

### ISSUE THREAD

**Issue by mgip** [nextapps-be/laravel-swagger-ui#17]
Hello,

How to generate openapi.json ??

I check this up the commands and i dont see any to generate Annotation based.

Thanks

**Comment by yinx** [comment]
Hey @mgip, 
This package does not generate an openapi.json file in any way.
Its only focus at this time is to allow you to add an openapi.json file and to smooth out the use of the swaggerui library to display that file as a web page.

**Comment by CrazyFreeMan** [comment]
Package allow set url for openapi json ?
