### ISSUE TITLE
Failed to load API definition on https

### ISSUE THREAD

**Issue by futurfuturfuturfutur** [nextapps-be/laravel-swagger-ui#31]
It works on local with http, but failed on stage environment with https
![Снимок экрана 2024-03-28 110103](https://github.com/nextapps-be/laravel-swagger-ui/assets/81389337/2c3d3651-4366-4888-8a18-a1fa1fe10b48)

**Comment by KarimpourMehrab** [comment]
when i added the current meta tag is error fixed !
in :  resources/views/index.blade.php
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">

**Comment by popovdk** [comment]
Set up forceScheme for env with https

```
class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        if($this->app->environment('production')) {
            \URL::forceScheme('https');
        }
    }
}
```
